---
title: "CRAN package popularity"
author: "@Andi@tech.lgbt"
output: 
  html_notebook: 
    code_folding: none
---


```{r}
library(tidyverse)
library(dlstats)
library(ggrepel)
library(lubridate)
```


`cran_stats` gives us downloads per month, so they will be incomplete for the current month. I'll exclude the current month to account for this, using the following variable:

```{r}
first_of_this_month <- floor_date(today(), unit = "month")
first_of_this_month
```

(Some) mixed models and SEM packages:

```{r}
pack_stats <-
  cran_stats(c("lme4", "nlme", "sem", "lavaan", "blme"))
```


```{r dpi = 300}
pack_stats %>%
  filter(start < first_of_this_month) %>%
  mutate(label = if_else(start == max(start),
                         as.character(package),
                         NA_character_)
         ) %>%
  ggplot(aes(
    x = start,
    y = downloads,
    colour = package,
    label = label
  )) +
  geom_smooth(se = FALSE) +
  geom_point() +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Date", y = "Downloads", colour = "Package") +
  geom_label_repel(na.rm = TRUE, segment.colour = NA) +
  theme(legend.position = "none") +
  scale_x_date(expand = expansion(mult = 0.2))
```


Packages for matching and propensity score weighting:

```{r}
match_packages <-
  cran_stats(c(
    "Matching",
    "MatchIt",
    "twang",
    "PSweight",
    "cem"
  ))
```


```{r}
match_packages %>%
  filter(start < first_of_this_month) %>%
  mutate(label = if_else(start == max(start),
                         as.character(package),
                         "")) %>%
  ggplot(aes(
    x = start,
    y = downloads,
    colour = package,
    label = label
  )) +
  geom_smooth(se = FALSE) +
  geom_point() +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Date", y = "Downloads", colour = "Package") +
  geom_label_repel(segment.colour = NA, point.size = NA, nudge_x = 200, direction = "y") +
  theme(legend.position = "none") +
  scale_x_date(expand = expansion(mult = 0.1))
```



