---
title: "Enumerating variations on evidence-based policymaking"
author: Andi Fugard
date: 9 Jan 2025
output: 
  html_notebook: 
    code_folding: none
---

That feeling when you want to see the 648 permutations of the words "evidence", "based", "policy", and "making", conjoined by space, hyphen, or just stuck together without either to make a closed compound word.


```{r message=FALSE, warning=FALSE}
library(tidyverse)
```


```{r}
word_orders <- function(words) {
  stopifnot(length(words) > 0)
  
  if (length(words) == 1) {
    res <- list(words)
  }
  else {
    res <- list()
    for (i in seq_along(words)) {
      next_list <- word_orders(words[-i])
      
      for (ws in next_list) {
        hyphen   <- c(words[i], "-", ws)
        space    <- c(words[i], " ", ws)
        compound <- c(words[i], ws)
        
        res <- c(res, list(hyphen, space, compound))
      }
    }
  }
  
  res
}
```


```{r}
res <- word_orders(c("evidence", "based", "policy", "making")) |>
  map_chr(\(x) paste(x, collapse = ""))
length(res)
```

```{r}
res
```



Karl Ove Hufthammer [offers](https://sciences.social/@huftis@toot.io/113799998896606542) this neat non-recursive solution, using {gtools}, {tidyr}, and {gdata}:

```{r}
words <- c("evidence", "based", "policy", "making")
seps <- c("-", " ", "")
n_words <- length(words)
n_seps <- length(seps)
perm_words <- gtools::permutations(n_words, n_words, words)
perm_seps <- gtools::permutations(n_seps, n_words - 1, seps, repeats.allowed = TRUE)
d <- tidyr::expand_grid(perm_words, perm_seps)
d2 <- gdata::interleave(t(d[1]), rbind(t(d[2]), ""))

res2 <- apply(d2, 2, paste0, collapse = "")
```


Same result:

```{r}
all(sort(res) == sort(res2))
```

