---
title: "Fingertips explorations"
author: Andi Fugard
output: html_notebook
---

```{r}
library(shinycssloaders)
#install.packages("fingertipsR", repos = "https://dev.ropensci.org")
library(fingertipsR)
library(tidyverse)
```


Useful info here: https://rstudio-pubs-static.s3.amazonaws.com/274982_54e369ab8e5c4702a99acb15c37cae88.html


```{r}
local_health_profiles <- profiles(ProfileName = "Local Health")
local_health_profiles$DomainID
```

```{r}
?fingertips_data
```



```{r}
all_local_dat <- fingertips_data(
  DomainID = local_health_profiles$DomainID,
  AreaTypeID = "All"
)
```


```{r}
str(all_local_dat)
```

```{r}
all_ward_dat <- all_local_dat %>%
  filter(AreaType == "Ward")
nrow(all_ward_dat)
```



```{r}
all_profiles <- profiles()
```

```{r}
View(all_profiles)
```

```{r}
all_profiles$DomainID
```


```{r}
area_types <- area_types()
```


```{r}
View(area_types)
```



```{r}
all_ward_dat <- fingertips_data(
  DomainID = all_profiles$DomainID,
  AreaTypeID = "8"
) %>%
  filter(AreaType == "Ward")
```




```{r}
all_ward_dat %>%
  group_by(IndicatorName, Timeperiod) %>%
  summarise(n = n(), valid = 100 * sum(!is.na(Value)) / n) %>%
  View()
```



```{r}
all_ward_dat <- fingertips_data(
  DomainID = all_profiles$DomainID,
  AreaTypeID = "8"
) %>%
  filter(AreaType == "Ward")
```

