---
title: "Hedges' g for MLMs -- exploring different methods"
author: "Andi Fugard ([@andi@sciences.social](https://sciences.social/@andi))"
date: "Last knitted `r format(Sys.Date(), '%d %B %Y')`"
output:
  html_notebook:
    code_folding: none
  html_document:
    df_print: paged
---

```{r}
library(lmeInfo)
library(nlme)
library(lme4)
library(eefAnalytics)
library(tictoc)
library(beepr)
library(brms)
library(tidybayes)
library(tidyverse)
```




```{r}
all_results <- list()

# vec_res order is estimate, lower, and upper 95% interval
add_result <- function(name, vec_res) {
  stopifnot(is.vector(vec_res))
  stopifnot(length(vec_res) == 3)
  stopifnot(vec_res[1] >= vec_res[2])
  stopifnot(vec_res[1] <= vec_res[3])
  stopifnot(vec_res[2] <= vec_res[3])
  res <- tibble(
    source  = name,
    est     = vec_res[1],
    lower95 = vec_res[2],
    upper95 = vec_res[3]
  )
  
  all_results <<- append(all_results, list(res))
}

clear_results <- function() {
  all_results <<- list()
}

tibble_results <- function() {
  bind_rows(all_results)
}
```


## eefAnalytics


```{r paged.print=FALSE}
output1 <- crtFREQ(
  Posttest ~ Intervention + Prettest,
  random = "School",
  intervention = "Intervention",
  data = crtData
)

summary(output1)
```


```{r}
output1$ES$Intervention1[2,]
```

```{r}
output1$Unconditional$ES$Intervention1[2,]
```


```{r}
add_result("eefAnalytics total conditional",
           output1$ES$Intervention1[2, ] |> as.numeric())
add_result(
  "eefAnalytics total unconditional",
  output1$Unconditional$ES$Intervention1[2, ] |> as.numeric()
)
```


```{r}
tibble_results()
```



## Naive approach using lme4


```{r}
test_mod <- lmer(Posttest ~ Intervention + Prettest +
                   (1|School), data = crtData)
test_mod |> summary()
```

```{r}
test_mod_0 <- lmer(Posttest ~ Intervention + (1|School), data = crtData)
test_mod_0
```

```{r}
vars <- VarCorr(test_mod_0) |> as.data.frame()
the_sd <- vars$vcov |> sum() |> sqrt()
the_sd
```

```{r}
vars 
```


```{r}
add_result("Naively divide CI by SD", 
c(fixef(test_mod)["Intervention"], confint(test_mod)["Intervention",]) |> as.numeric() / the_sd)
```

```{r}
tibble_results()
```



## g_mlm in {lmeInfo}

```{r}
lme_num <- lme(
  fixed = Posttest ~ Intervention + Prettest,
  random = ~ 1 | School,
  data = crtData,
  method = "REML"
)

lme_den <- lme(
  fixed = Posttest ~ Intervention,
  random = ~ 1 | School,
  data = crtData,
  method = "REML"
)
```


```{r paged.print=FALSE}
summary(lme_num)
```



```{r}
the_g <- g_mlm(
  lme_num,
  p_const = c(0,1,0),
  mod_denom = lme_den,
  r_const = c(1,1),
  infotype = "expected",
  separate_variances = FALSE
)

the_g
```


Without the df adjustment:

```{r}
unadj_SE <- sqrt(the_g$SE_g_AB^2 / the_g$J_nu^2)
the_g$delta_AB
c(the_g$delta_AB - 1.96 * unadj_SE,
  the_g$delta_AB + 1.96 * unadj_SE)
```

"Manual" df adjustment:

```{r}
the_g$J_nu * the_g$delta_AB
```

From the model:

```{r}
the_g$g_AB
c(the_g$g_AB - 1.96 * the_g$SE_g_AB,
  the_g$g_AB + 1.96 * the_g$SE_g_AB)
```

```{r}
add_result("lmeInfo Hedges df adjusted", c(the_g$g_AB,
                                           the_g$g_AB - 1.96 * the_g$SE_g_AB,
                                           the_g$g_AB + 1.96 * the_g$SE_g_AB))
add_result("lmeInfo unadjusted", c(the_g$delta_AB,
                                   the_g$delta_AB - 1.96 * unadj_SE,
                                   the_g$delta_AB + 1.96 * unadj_SE))
```


```{r}
tibble_results()
```


## Manually, with the help of {merDeriv}


```{r}
my_g <- fixef(test_mod)["Intervention"] / the_sd
my_g
```


```{r}
b_var <- vcov(test_mod)["Intervention", "Intervention"]
b_var
```

```{r}
library(merDeriv)
ranef_var <- vcov(test_mod_0,
                  full = TRUE,
                  ranpar = "var",
                  information = "expected")[3, 3]

sum_vars <- vars$vcov |> sum()
the_se <- sqrt((b_var / sum_vars) +
       ((fixef(test_mod)["Intervention"]^2 * ranef_var) / (4 * (sum_vars)^3)))
```

```{r}
the_se
```


```{r}
add_result("Manual using merDeriv (no df adjust)", c(my_g,
                                      my_g - 1.96 * the_se,
                                      my_g + 1.96 * the_se))
```


```{r}
tibble_results()
```



## Try some bootstrapping with {lmersampler}


```{r}
library(lmeresampler)
```



```{r}
to_boot <- lmer(Posttest ~ Intervention + Prettest +
                  (1 | School), data = crtData)
```



```{r}
each_boot <- function(mod) {
  denom_mod <- lmer(Posttest ~ Intervention + (1 | School),
                    data = model.frame(mod))
  
  vars   <- VarCorr(denom_mod) |> as.data.frame()
  the_sd <- vars$vcov |> sum() |> sqrt()
  
  the_b  <- fixef(mod)["Intervention"]
  the_es <- the_b / the_sd
  
  c(b = the_b, sd = the_sd, g = the_es)
}
```


```{r}
each_boot(to_boot)
```

```{r}
how_many_boots <- 5000
```



```{r}
tic()
boo_para <- bootstrap(
  model = to_boot,
  .f    = each_boot,
  type  = "parametric",
  B = how_many_boots 
)
toc()
beep(3)
```


```{r}
tic()
boo_resid <- bootstrap(
  model = to_boot,
  .f    = each_boot,
  type  = "residual",
  B = how_many_boots 
)
toc()
beep(2)
```


```{r}
tic()
boo_case <- bootstrap(
  model = to_boot,
  .f    = each_boot,
  type  = "case",
  B = how_many_boots ,
  resample = c(TRUE, TRUE)
)
toc()
beep(1)
```


```{r}
confint(boo_para, type = "perc")
```


```{r}
confint(boo_resid, type = "perc")
```


```{r}
confint(boo_case, type = "perc")
```



```{r}
get_bootstrap_ests <- function(obj) {
  mean_est <- obj$replicates$g.Intervention  |> mean()
  intervals <- confint(obj, type = "perc") |>
  filter(term == "g.Intervention")
  
  c(mean_est, intervals$lower, intervals$upper) |> as.numeric()
}
```

```{r}
add_result("bootstrap (parametric)", get_bootstrap_ests(boo_para))
add_result("bootstrap (resid)",      get_bootstrap_ests(boo_resid))
add_result("bootstrap (case)",       get_bootstrap_ests(boo_case))
```


```{r}
tibble_results()
```



## Go Bayesian


Model for the numerator:

```{r}
bayes_mod_1 <- brm(Posttest ~ Intervention + Prettest +
                     (1 | School), data = crtData)
```

Model for the denominator:

```{r}
bayes_mod_0 <- brm(Posttest ~ Intervention +
                     (1 | School), data = crtData)
```



```{r}
bayes_mod_0 |> get_variables()
```


```{r}
b_draws <- bayes_mod_1 |>
  spread_draws(b_Intervention)
sd_draws <- bayes_mod_0 |>
  spread_draws(sd_School__Intercept, sigma) |>
  mutate(total_sd = sqrt(sd_School__Intercept^2 + sigma^2))
```

```{r}
head(b_draws)
```


```{r}
head(sd_draws)
```

```{r}
combined_draws <- bind_cols(b_draws |> select(b_Intervention),
                      sd_draws |> select(total_sd)) |>
  mutate(g = b_Intervention / total_sd)
head(combined_draws)
```


```{r}
combined_draws_Bayes_mean <- combined_draws |>
  mean_hdci(g)
combined_draws_Bayes_median <- combined_draws |>
  median_hdci(g)
combined_draws_Bayes_mode <- combined_draws |>
  mode_hdci(g)
```




```{r}
add_result("Bayesian HDCI (mean)",   combined_draws_Bayes_mean[,1:3] |> as.numeric())
add_result("Bayesian HDCI (median)", combined_draws_Bayes_median[,1:3] |> as.numeric())
add_result("Bayesian HDCI (mode)",   combined_draws_Bayes_mode[,1:3] |> as.numeric())
```



## Try {eefAnalytics}' Bayes model


```{r}
eefBayes <- crtBayes(
  Posttest ~ Intervention + Prettest,
  random = "School",
  intervention = "Intervention",
  nsim = 4000,
  data = crtData
)
```



```{r}
eefBayes
```


```{r}
add_result("eefAnalytics Bayes total conditional",
           eefBayes$ES$Intervention1[2, ] |> as.numeric())
add_result(
  "eefAnalytics Bayes total unconditional",
  eefBayes$Unconditional$ES$Intervention1[2, ] |> as.numeric()
)
```



## Summary of all approaches

```{r rows.print = 20}
tibble_results() |>
  mutate(CIwidth = upper95 - lower95) |>
  mutate(across(where(is.numeric), ~ round(.x, 2))) |>
  arrange(CIwidth, est)
```


