---
title: "View M136279841"
author: "Andi Fugard"
date: "23 Oct 2024"
output:
  html_document:
    df_print: paged
  html_notebook:
    code_folding: none
---


Load in some packages:

```{r}
library(conflicted)
library(tidyverse)
```

Download the digits (in a zip file) from https://www.mersenne.org/primes/?press=M136279841

```{r}
temp_dir  <- tempdir(check = TRUE)
temp_file <- tempfile(pattern = "primezip",
                      tmpdir = temp_dir)
download.file("https://www.mersenne.org/primes/digits/M136279841.zip",
              temp_file)
```

Unzip:

```{r}
unzip(temp_file, files = "m136279841.txt", exdir = temp_dir)
```


Load it into R:

```{r}
filename <- paste(temp_dir, "m136279841.txt", sep = "\\")
digits_str <- readLines(filename) |> paste(collapse = "")
```


Transform into a 1D vector of digits:

```{r}
digits <- digits_str |>
  strsplit("") |>
  pluck(1) |>
  as.numeric()
```


Check the first and last three digits:

```{r}
digits[1:3]
digits[(length(digits) - 2):length(digits)]
```

Count all the digits:

```{r}
length(digits)
```

Make a few tables and a pic:

```{r}
dig_table <- table(digits) |> as.data.frame()
```


```{r}
dig_table <- dig_table |>
  mutate(perc = 100 * Freq / sum(Freq))
dig_table
```


```{r dpi=300}
dig_table |>
  ggplot(aes(x = digits, y = Freq)) +
  geom_point() +
  labs(x = "Digit", y = "Frequency", title = "Digit frequency in M136279841") +
  theme(legend.position = "none")
```

```{r}
dig_table |> arrange(Freq)
```

Are the digits all equally likely?

```{r}
chisq.test(dig_table$Freq)
```

```{r}
chisq.test(dig_table$Freq)$stdres
```

No evidence they aren't.

How much more frequent would the 3 need to be to get a statistically significant $\chi^2$?

```{r}
sens_check <- dig_table$Freq
the_p <- chisq.test(sens_check)$p.value
add_on <- 0

while (the_p > .05) {
  add_on <- add_on + 1
  sens_check[4] <- dig_table$Freq[4] + add_on
  the_p <- chisq.test(sens_check)$p.value
}

add_on
```

```{r}
chisq.test(sens_check)
```

```{r}
chisq.test(sens_check)$stdres
```


```{r dpi=300}
dig_table |>
  mutate(Freq = sens_check) |>
  ggplot(aes(x = digits, y = Freq)) +
  geom_point() +
  labs(x = "Digit", y = "Frequency", title = "Mini freq for 3 needed to get a chi-square test with p < .05") +
  theme(legend.position = "none")
```


```{r}
twogram <- function(test_vec) {
  res <- matrix(0, nrow = 10, ncol = 10)
  rownames(res) <- 0:9
  colnames(res) <- 0:9
  for (i in 1:(length(test_vec) - 1)) {
    res[test_vec[i] + 1,
        test_vec[i + 1] + 1] <- res[test_vec[i] + 1,
                                    test_vec[i + 1] + 1] + 1
  }
  res
}
```

```{r}
two_grams <- twogram(digits)
```

```{r}
two_grams - min(two_grams)
```

```{r}
chisq.test(two_grams)
```


