---
title: "Mediation confound"
output: html_notebook
---


```{r}
library(tidyverse)
```


Example with a mediator-outcome confounder.

```{r}
n <- 1000

dat <- tibble(
  treat             = rbinom(n, 1, .5),
  med_out_confound  = rnorm(n, 0, 2),
  med               = treat + med_out_confound + rnorm(n, 0, 1),
  out               = treat + med_out_confound + rnorm(n, 0, 1)
)
```


```{r}
med_fit <- lm(med ~ treat, data = dat)
out_fit <- lm(out ~ med + treat, data = dat)
```


```{r}
library(mediation)
```


```{r}
mediate1 <-
  mediate(
    med_fit,
    out_fit,
    treat = "treat",
    mediator = "med",
    robustSE = TRUE,
    sims = 100
  )
```

```{r}
summary(mediate1)
```


```{r}
mediate1_sens <-
  medsens(mediate1,
          rho.by = 0.1,
          effect.type = "both",
          sims = 100)

```

```{r}
summary(mediate1_sens)
```


```{r}
old <- par(mfrow = c(1,2))
  plot(mediate1_sens)
par(old)
```

```{r}
cor.test(~ med_out_confound + out, data = dat)
```



```{r}
med_fit2 <- lm(med ~ treat + med_out_confound, data = dat)
out_fit2 <- lm(out ~ med + med_out_confound + treat, data = dat)
```


```{r}
mediate2 <-
  mediate(
    med_fit2,
    out_fit2,
    treat = "treat",
    mediator = "med",
    robustSE = TRUE,
    sims = 100
  )
summary(mediate2)
```



```{r}
mediate2_sens <-
  medsens(mediate2,
          rho.by = 0.1,
          effect.type = "both",
          sims = 100)

```


```{r}
summary(mediate2_sens)
```

```{r}
old <- par(mfrow = c(1,2))
  plot(mediate2_sens)
par(old)
```



Try again, this time without confounding.


```{r}
n <- 1000

dat2 <- tibble(
  treat = rbinom(n, 1, .5),
  med   = 2*treat + rnorm(n, 0, 1),
  out   = 3*med + rnorm(n, 0, 1)
)
```



```{r}
med_fit3 <- lm(med ~ treat, data = dat2)
out_fit3 <- lm(out ~ med + treat, data = dat2)
```


```{r}
mediate3 <-
  mediate(
    med_fit3,
    out_fit3,
    treat = "treat",
    mediator = "med",
    robustSE = TRUE,
    sims = 100
  )
summary(mediate3)
```

```{r}
mediate3_sens <-
  medsens(mediate3,
          rho.by = 0.1,
          effect.type = "both",
          sims = 100)

```

```{r}
summary(mediate3_sens)
```


```{r}
old <- par(mfrow = c(1,2))
  plot(mediate3_sens)
par(old)
```