---
title: "The bargraphs of evaluation approaches"
author: "Andi Fugard"
date: "5 March 2026"
output:
  html_document:
    df_print: paged
  html_notebook:
    code_folding: none
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

Data from the petals in:

Schröter, D., Becho, L. W., & Montrosse-Moorhead, B. (2026). [The garden of evaluation approaches: Supporting explicit, theory-informed evaluation practice.](https://journals.sagepub.com/doi/abs/10.1177/13563890261421931) _Evaluation._


```{r}
dat <- read.csv(text = "Approach	Values	Valuing	Activism for social justice	Context	Promoting use	Engagment breadth	Engagement depth	Power dynamics in making evaluation decisions
ISE4GEMs	3	3	3	3	3	3	3	3
Made in Africa Evaluation	3	2	3	3	2	3	3	3
Nation to Nation Evaluation	3	1	3	3	2	3	3	3
Sistematización de Experiencias	3	1	3	2	3	3	3	3
Transformative Participatory Evaluation	3	0	3	3	3	3	3	3
Fourth Generation Evaluation	3	3	1	2	2	3	3	3
Most Significant Change	3	3	0	3	3	2	2	2
Outcomes Harvesting	2	2	1	3	3	2	3	2
Success Case Method	3	2	0	3	3	1	2	2
Adaptive Evaluation	2	2	1	3	3	1	2	1
Practical Participatory Evaluation	2	0	1	3	3	1	3	2
Theory-Driven Evaluation	2	1	1	2	2	2	2	2
Realist Evaluation	1	1	1	3	2	2	2	1", sep = "\t", check.names = FALSE)
```

```{r}
dat
```

```{r}
dat_long <- pivot_longer(dat, cols = 2:9, names_to = "Dimension") |>
  arrange(desc(Approach)) |>
  mutate(Approach = fct_inorder(Approach))
```



```{r fig.height=15, fig.width=8, dpi = 300}
ggplot(dat_long, aes(x = Approach, y = value, fill = Approach)) +
  geom_col() +
  facet_wrap(~ Dimension, ncol = 2) +
  labs(
    x = NULL,
    y = "Rating",
    title = "The bargraphs of evaluation approaches"
  ) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        axis.line = element_line()) +
  coord_flip()
```






