---
title: "Packages for making pretty tables in R"
output:
  html_notebook: default
  word_document: default
---


# gt

```{r}
library(gt)
library(tidyverse)
```

```{r}
sleep_sum <- sleep %>%
  group_by(group) %>%
  summarise(Mean = mean(extra),
            SD   = sd(extra),
            n    = n())
```


```{r}
sleep_sum %>%
  select(Group = group, everything()) %>%
  gt() %>%
  fmt_number(columns = c(Mean, SD),
             decimals = 2)
```


```{r}
dat <- expand.grid(Month = c(0, 3, 6, 12),
                   ID    = 1:100) %>%
  tibble()

dat <- tibble(ID    = unique(dat$ID),
              Treat = rbinom(length(ID), 1, 0.5)) %>%
       left_join(dat)

dat <- dat %>%
  mutate(Baseline = rnorm(nrow(dat), 10, 1),
         Y        = Baseline + (1/6) * Month +
                               (3/6) * Month * Treat,
         Group    = factor(Treat, labels = c("Control", "Treat")))

dat
```


```{r}
dat %>%
  ggplot(aes(x = Month, y = Y,group = ID, colour = Group)) +
  geom_point() +
  geom_line()
```


```{r}
dat_sum <- dat %>%
  group_by(Group, Month) %>%
  summarise(Mean = mean(Y),
            SD   = sd(Y),
            n    = n())
dat_sum
```

```{r}
dat_sum_wide <- dat_sum %>%
  pivot_wider(names_from = Group,
              values_from = c(Mean, SD, n))
dat_sum_wide
```

```{r}
my_tab <- dat_sum_wide %>%
  gt() %>%
  tab_spanner(
    label = md("**Treatment**"),
    columns = c(Mean_Treat, SD_Treat, n_Treat)
  ) %>%
  tab_spanner(
    label = md("**Control**"),
    columns = c(Mean_Control, SD_Control, n_Control)
  ) %>%
  cols_label(
    Mean_Control = md("**M**"),
    Mean_Treat = md("**M**"),
    SD_Treat = md("**SD**"),
    SD_Control = md("**SD**"),
    n_Treat = md("**n**"),
    n_Control = md("**n**"),
    Month = md("**Month**")
  ) %>%
  fmt_number(columns = starts_with(c("Mean", "SD")),
             decimals = 2)
```

```{r}
my_tab
```

This saves the table out:

```{r}
gtsave(my_tab, "gt.rtf")
```

It's not very pretty, tbh.




# flextable

```{r}
library(flextable)
library(officer)
```

This is rather hacky... but off we go:

```{r}
flex_tab_test <- dat_sum_wide %>%
  mutate(buffer = "") %>%
  select(Month, ends_with("_Treat"),
                buffer,
                ends_with("_Control")) %>%
  flextable() %>%
  set_header_labels(
    Mean_Treat = "Mean",
    Mean_Control = "Mean",
    SD_Treat = "SD",
    SD_Control = "SD",
    n_Treat = "n",
    n_Control = "n",
    buffer = ""
  ) %>%
  add_header_row(values = c("", "Treat", "", "Control"),
                 colwidths = c(1, 3, 1, 3)) %>%
  colformat_double(j = dat_sum_wide %>%
                          select(starts_with("Mean"),                                                     starts_with("SD"))
                          %>% names(),
                   digits = 2) %>%
  align(i = 1, align = "center", part = "header") %>%
  border_remove() %>%
  hline_top(part = "header", border = fp_border(width = 1)) %>%
  hline(i = 1, j = c(2,6), border = fp_border(width = 1),
                           part = "header") %>%
  hline(i = 2, border = fp_border(width = 1),
               part = "header") %>%
  hline(i = nrow(dat_sum_wide), border = fp_border(width = 1),
                                part = "body") %>%
  bold(bold = TRUE, part = "header")

flex_tab_test
```

```{r}
save_as_docx(flex_tab_test, path = "flextab.docx")
```



# huxtable

```{r}
library(huxtable)
```

Half way there...

```{r}
hux_test <- dat_sum_wide %>%
  mutate(buffer = "") %>%
  select(Month, ends_with("_Treat"),
                buffer,
                ends_with("_Control")) %>%
  as_hux() %>%
  set_contents(1, 2:4, c("Mean", "SD", "n")) %>%
  set_contents(1, 5, "") %>%
  set_contents(1, 6:8, c("Mean", "SD", "n")) %>%
  insert_row("", "Treat", "", "","", "Control", "","",
             after = 0) %>%
  merge_cells(1, 2:4) %>% 
  merge_cells(1, 6:8) %>%
  theme_article() %>%
  set_bottom_border(row = 1, col = c(2:4, 6:8), value = brdr(1)) %>%
  set_align(1, everywhere, "center") 


hux_test
```

```{r}
quick_docx(hux_test, file = "huxtable.docx")
```



