---
title: "Playing with QCA"
output: html_notebook
---

```{r}
library(QCA)
```


```{r}
generate(S +  ~S + P -> C)
```




```{r}
madeup <- data.frame(A = rep(1,100), C = rbinom(100, 1, .5))
madeup$B <- madeup$A
madeup$B[1] <- 0
madeup$out <- madeup$B
```

```{r}
summary(madeup)
```

```{r}
madeup
```



```{r}
madeup |>
  truthTable(out) |>
  minimize()
```
```{r}
rpart(
    out ~ A + B + C,
    data = madeup,
    control = rpart.control(minsplit = 20)
  ) |>
rpart.plot::rpart.plot(type = 3)
```




```{r}
LC
```



```{r}
ttLC <- truthTable(LC, SURV, sort.by = "incl, n", show.cases = TRUE, details = TRUE)
cLC <- minimize(ttLC)
cLC
```

```{r}
LC$DEV <- as.factor(LC$DEV)
LC$URB <- as.factor(LC$URB)
LC$LIT <- as.factor(LC$LIT)
LC$IND <- as.factor(LC$IND)
LC$STB <- as.factor(LC$STB)
```



```{r}
library(rpart)
```


```{r}
cart1 <-
  rpart(
    SURV ~ DEV + URB + LIT + IND + STB,
    data = LR,
    control = rpart.control(minsplit = 2, minbucket = 1, cp = 0.05, xval = 100)
  )
rpart.plot::rpart.plot(cart1, type = 3)
```



Random

```{r}
set.seed(44)

rand_dat <- data.frame(
  experienced = rbinom(30, 1, .5),
  attended_leadership_training = rbinom(30, 1, .5),
  studied_psych = rbinom(30, 1, .5),
  studied_stats = rbinom(30, 1, .5),
  good_leader  = rbinom(30, 1, .5)
)

rand_dat |>
  truthTable(good_leader) |>
  minimize(details = TRUE)
```


```{r}
rpart(good_leader ~ .,
      data = rand_dat,
      control = rpart.control(
        minsplit = 10,
        cp = .01
      )) |>
  rpart.plot::rpart.plot(type = 3)
```






```{r}
cart2 <-
  rpart(
    SURV ~ DEV + URB + LIT + IND + STB,
    data = LC,
    control = rpart.control(minsplit = 2, cp = 0, xval = 100)
  )
summary(cart2)
rpart.plot::rpart.plot(cart2, type = 3)
```


```{r}
lm_mod <- lm(SURV ~ (DEV + URB + LIT + IND + STB)^2, data = LR)
lm_step <- step(lm_mod, direction = "both", k = 2.5)
summary(lm_step)
```


```{r}
library(car)
```


```{r}
vif(lm_mod, type = "predictor")
```


