---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(qsimulatR)
```


```{r}
qstate(nbits = 1, coef = c(1,0))
```

```{r}
qstate(nbits = 1, coef = c(0,1))
```


```{r}
H(1) * qstate(nbits = 1, , coef = c(0,1))
H(1) * qstate(nbits = 1, , coef = c(1,0))
```

```{r}
qstate(nbits = 2, coefs = c(1,0,0,0))
qstate(nbits = 2, coefs = c(0,1,0,0))
qstate(nbits = 2, coefs = c(0,0,1,0))
qstate(nbits = 2, coefs = c(0,0,0,1))
```



```{r}
CNOT() * qstate(nbits = 2, coefs = c(1,0,0,0))
CNOT() * qstate(nbits = 2, coefs = c(0,1,0,0))
CNOT() * qstate(nbits = 2, coefs = c(0,0,1,0))
CNOT() * qstate(nbits = 2, coefs = c(0,0,0,1))
```


```{r}
CNOT() * (H(1) * qstate(nbits = 2, coefs = c(1,0,0,0)))
```


```{r}
bc00 <- CNOT() * (H(1) * 
                  qstate(nbits = 2, coefs = c(1,0,0,0)))
measure(bc00, rep = 10000) |> summary()
```




Try the Bell circuits in Section 10.4.

```{r}
bell <- function(coefs) {
  inputs <- qstate(nbits = 2,
                   coefs = coefs,
                   basis = c("|00>","|10>","|01>","|11>"))
                   # This basis order gives the same
                   # results as the book
  
  cat("Input: ")   # For debugging
  print(inputs)
  cat("\n")

  CNOT() * (H(1) * inputs)
}
```




```{r}
bell(c(1,0,0,0))
bell(c(0,1,0,0))
bell(c(0,0,1,0))
bell(c(0,0,0,1))
```



```{r}
RBC <- H(1) * (CNOT() * bell(c(1,0,0,0)))
RBC
```

```{r dpi = 300}
RBC |> plot()
```



```{r}
export2qiskit(RBC, filename = "rbc.py")
```






```{r}
silly <- (H(1) * qstate(1))
plot(silly)
```


```{r}
measure(silly, rep = 1000) |> summary()
```


```{r}
genComputationalBasis(2)
```




