---
title: "Playing around with reduce, Reduce, and foldr1"
author: Andi Fugard
date: 5 Jan 2025
output: 
  html_notebook: 
    code_folding: none
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```


```{r}
set.seed(20250104)
A <- data.frame(id = 1:3, x = rnorm(3))
B <- data.frame(id = c(2, 3), y = rnorm(2))
C <- data.frame(id = c(1, 3), z = rnorm(2))
```

```{r}
A
B
C
```

Alexander Krannich's [example](https://www.linkedin.com/posts/alexander-krannich_rstats-statistics-rstudio-activity-7281670805879459840-zVZO):

```{r}
list(A, B, C) |>
  reduce(full_join, by = "id")
```

Using only {base} (mild edit of David Souza's [reply](https://www.linkedin.com/feed/update/urn:li:activity:7281670805879459840?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7281670805879459840%2C7281814659072970753%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287281814659072970753%2Curn%3Ali%3Aactivity%3A7281670805879459840%29)):

```{r}
list(A, B, C) |>
  Reduce(\(x, y) merge(x, y, by = "id", all = TRUE), x = _)
```

Getting silly -- this all reminded me of Haskell's [foldr1](https://hackage.haskell.org/package/base-4.21.0.0/docs/Prelude.html#v:foldr1), implemented (without the Currying) as:

```{r}
foldr1 <- \(f, xs) {
  if (length(xs) == 1)
    xs[[1]]
  else
    f(xs[[1]], foldr1(f, tail(xs, length(xs) - 1)))
}

foldr1(\(x, y) merge(x, y, by = "id", all = TRUE), list(A, B, C))
```

Here is an easier example:

```{r}
foldr1(`+`, 1:10)
```

Which is the same as:

```{r}
sum(1:10)
```


