---
title: "teffects ra, with bootstrapped SE, in R"
author: "Andi Fugard ([@andi@sciences.social](https://sciences.social/@andi))"
date: 16 August 2024
output: 
  html_notebook: 
    code_folding: none
---

```{r}
library(conflicted)
library(tidyverse)
library(haven)
library(boot)
library(tictoc)
library(beepr)
library(car)
```

```{r}
dat <- read_dta("https://www.stata-press.com/data/r14/cattaneo2.dta")
```


Try to replicate the example at:

https://www.stata.com/manuals/teteffectsra.pdf#teteffectsra

ATE is -239.6392, SE = 23.82402, z = -10.06, 95% CI = [-286.3334, -192.945].

ATT is -223.3017, SE = 22.7422, z = -9.82, 95% CI = [-267.8755, -178.7278].

```{r}
boot_ate <- function(d, i) {
  the_dat <- d[i,]
  dat0 <- the_dat |> dplyr::filter(mbsmoke == 0)
  dat1 <- the_dat |> dplyr::filter(mbsmoke == 1)
  lm0 <- lm(bweight ~ prenatal1 + mmarried + mage + fbaby, data = dat0)
  lm1 <- lm(bweight ~ prenatal1 + mmarried + mage + fbaby, data = dat1)
  
  dat0 <- dat0 |>
    mutate(bweight_0 = bweight,
           bweight_1 = predict(lm1, newdata = dat0))
  
  dat1 <- dat1 |>
    mutate(bweight_1 = bweight,
           bweight_0 = predict(lm0, newdata = dat1))
  
  dat_all <- bind_rows(dat0, dat1) |>
    mutate(te = bweight_1 - bweight_0)
  
  res_ATE <- dat_all |>
    summarise(ate = mean(te))
  
  res_ATT <- dat_all |>
    dplyr::filter(mbsmoke == 1) |>
    summarise(att = mean(te))
  
  c(ate = res_ATE$ate, att = res_ATT$att)
}
```


```{r}
boot_ate(dat, 1:nrow(dat))
```

```{r}
tic()
boots <- boot(data = dat, statistic = boot_ate, R = 1499)
toc()
beep(2)
```


```{r}
res <- summary(boots) |> as.data.frame()
rownames(res) <- names(boots$t0)
res
```




