---
title: "R Notebook"
output: html_notebook
---



```{r}
library(googlesheets4)
library(tidyverse)
library(ggrepel)
```

https://docs.google.com/spreadsheets/u/0/d/1gVHNx4kzXd947AFfQGiJg5zJrdNXrM81t2OC8UJFnw8/htmlview

```{r}
dat <- read.csv("Ministerial resignations outside reshuffles since 1979 - Sheet1.csv") |>
  mutate(Date_d = parse_date_time(Date, orders = "dmy"))
dat
```
 


```{r}
govs <- read.csv(text =
"PM,StartDate,EndDate
Thatcher,1979-05-04,1990-11-28
Major,1990-11-28,1997-05-02
Blair,1997-05-02,2007-06-27
Brown,2007-06-27,2010-05-11
Cameron,2010-05-11,2016-07-13
May,2016-07-13,2019-07-24
Johnson,2019-07-24,2022-09-06
Truss,2022-09-06,2022-10-25
Sunak,2022-10-25,2024-07-05
Starmer,2024-07-05,") |>
  mutate(EndDate = if_else(PM == "Starmer", format(Sys.Date(), "%Y-%m-%d"), EndDate)) |>
  mutate(StartDate = parse_date_time(StartDate, "ymd"),
         EndDate = parse_date_time(EndDate, "ymd")) |>
  mutate(term_years = time_length(interval(StartDate, EndDate), unit = "year"))
govs
```


```{r}
govs[]
```



```{r}
dat <- left_join(dat, govs) |>
  mutate(years_since_start = time_length(interval(StartDate, Date_d), unit = "year"))
```




```{r}
dat |>
  count(Type)
```




```{r}
dat |>
  group_by(PM) |>
  filter(Rank %in% c("MoS", "PUSS")) |>
  filter(Type == "Disagreement") |>
  count(Rank) |>
  pivot_wider(names_from = Rank, values_from = n, values_fill = 0) |>
  mutate(MoS_prop = MoS / (MoS + PUSS)) |>
  arrange(MoS_prop)
```



```{r}
cum_all <- dat |>
  group_by(PM, StartDate, years_since_start) |>
  tally() |>
  arrange(StartDate, years_since_start) |>
  group_by(PM) |>
  mutate(cumsum = cumsum(n))
cum_all 
```


```{r}
cum_all |>
  ggplot(aes(x = years_since_start, y = cumsum, colour = PM)) +
  geom_step()
```





```{r}
cum_dis <- dat |>
  filter(Type == "Disagreement") |>
  group_by(PM, StartDate, years_since_start) |>
  tally() |>
  arrange(StartDate, years_since_start) |>
  group_by(PM) |>
  mutate(cumsum = cumsum(n))
cum_dis 
```





```{r}
last_points <- cum_dis |>
  group_by(PM) |>
  slice_max(years_since_start, n = 1)

cum_dis |>
  ggplot(aes(x = years_since_start, y = cumsum, colour = PM)) +
  geom_step() +
  geom_text_repel(
    data = last_points,
    aes(label = PM),
    nudge_x = 0.5,
    direction = "y",
    hjust = 0,
    size = 4
  ) +
  coord_cartesian(clip = "off") +
  theme(legend.position = "none")
```

```{r}
last_points <- cum_all |>
  group_by(PM) |>
  slice_max(years_since_start, n = 1)

cum_all |>
  ggplot(aes(x = years_since_start, y = cumsum, colour = PM)) +
  geom_step() +
  geom_text_repel(
    data = last_points,
    aes(label = PM),
    nudge_x = 0.5,
    direction = "y",
    hjust = 0,
    segment.colour = "black"#,
    #colour = "black"
  ) +
  #coord_cartesian(clip = "off") +
  theme(legend.position = "none") +
  xlim(0, 13) +
  labs(x = "Year", y = "Resignations")
```


```{r}
last_vals <- cum_dis |> group_by(PM) |>
  slice_max(cumsum, n = 1, with_ties = FALSE) |>
  ungroup() |>
  select(-years_since_start) |>
  left_join(govs |> select(PM, years_since_start = term_years))
last_vals
```

```{r}
first_vals <- last_vals |>
  mutate(n = 0, cumsum = 0, years_since_start = 0)
first_vals
```


```{r}
cum_dis <- bind_rows(first_vals, cum_dis, last_vals)
```


```{r}
keep_PM <- c("Starmer", "May", "Brown", "Johnson", "Blair", "Thatcher")

last_points <- cum_dis |>
  filter(PM %in% keep_PM) |>
  group_by(PM) |>
  slice_max(years_since_start, n = 1)

cum_dis |>
  filter(PM %in% keep_PM) |>
  ggplot(aes(x = years_since_start, y = cumsum, colour = PM)) +
  geom_step(linewidth = 1.1) +
  geom_text_repel(
    data = last_points,
    aes(label = PM),
    nudge_x = ifelse(last_points$PM == "Starmer", -0.4, 0.2),
    nudge_y = ifelse(last_points$PM == "Starmer", 0.4, 0),
  ) +
  theme(legend.position = "none") +
  ylim(0, 40) +
  xlim(0, 14) +
  labs(x = "Year", y = "Cumulative sum", title = "Resignations coded as \"disagreement\"", caption = "Data from Institute for Government at\nhttps://docs.google.com/spreadsheets/u/0/d/1gVHNx4kzXd947AFfQGiJg5zJrdNXrM81t2OC8UJFnw8/htmlview") +
  scale_x_continuous(breaks = scales::breaks_width(1))
```

```{r}
last_points
```



```{r}
dat |>
  group_by(PM, StartDate) |>
  filter(Type == "Disagreement") |>
  count(Rank) |>
  mutate(sum = sum(n)) |>
  pivot_wider(names_from = "Rank", values_from = n, values_fill = 0) |>
  mutate(`PUSS %` = 100*PUSS/sum,
         `PUSS %` = round(`PUSS %`, 1)) |>
  select(PUSS, sum, `PUSS %`) |>
  arrange(StartDate) |>
  ungroup() |>
  select(-StartDate)
```

