---
title: "Synth"
output: html_notebook
---

```{r}
library(conflicted)
library(tidyverse)
library(tidysynth)
library(WeightIt)
library(marginaleffects)
conflicts_prefer(dplyr::filter)
```

```{r}
smoking |>
  arrange(state, year)
```


```{r}
View(smoking)
```


```{r}
```


```{r}
smoking_out <-
  smoking %>%
  
  # initial the synthetic control object
  synthetic_control(outcome = cigsale, # outcome
                    unit = state, # unit index in the panel data
                    time = year, # time index in the panel data
                    i_unit = "California", # unit where the intervention occurred
                    i_time = 1988, # time period when the intervention occurred
                    generate_placebos = T # generate placebo synthetic controls (for inference)
                    ) %>%
  
  # Generate the aggregate predictors used to fit the weights
  
  # average log income, retail price of cigarettes, and proportion of the
  # population between 15 and 24 years of age from 1980 - 1988
  generate_predictor(time_window = 1980:1988,
                     ln_income = mean(lnincome, na.rm = T),
                     ret_price = mean(retprice, na.rm = T),
                     youth = mean(age15to24, na.rm = T)) %>%
  
  # average beer consumption in the donor pool from 1984 - 1988
  generate_predictor(time_window = 1984:1988,
                     beer_sales = mean(beer, na.rm = T)) %>%
  
  # Lagged cigarette sales 
  generate_predictor(time_window = 1975,
                     cigsale_1975 = cigsale) %>%
  generate_predictor(time_window = 1980,
                     cigsale_1980 = cigsale) %>%
  generate_predictor(time_window = 1988,
                     cigsale_1988 = cigsale) %>%
  
  
  # Generate the fitted weights for the synthetic control
  generate_weights(optimization_window = 1970:1988, # time to use in the optimization task
                   margin_ipop = .02,sigf_ipop = 7,bound_ipop = 6 # optimizer options
  ) %>%
  
  # Generate the synthetic control
  generate_control()
```


```{r}
smoking_out |> grab_synthetic_control() |>
  mutate(att = real_y - synth_y)
```







```{r}
smoking_out
```


```{r}
the_dat <- (smoking_out %>% plot_differences())$data
the_dat
```



```{r}
plot_weights(smoking_out)
```




# Try entropy matching



```{r}
control_preds <- smoking_out |>
  grab_predictors(type = "controls") |>
  pivot_longer(cols = Alabama:Wyoming) |>
  pivot_wider(names_from = variable, values_from = value) |>
  mutate(treat = 0)
treat_preds <- smoking_out |> 
  grab_predictors() |> 
  pivot_longer(cols = "California") |>
  pivot_wider(names_from = variable, values_from = value) |>
  mutate(treat = 1)

covs <- bind_rows(control_preds, treat_preds) |>
  rename(state = name)
covs
```




```{r}
outcome_dat <- smoking |>
  filter(year >= 1989) |>
  select(state, year, cigsale) |>
  mutate(treat = as.numeric(state == "California")) |>
  pivot_wider(
    id_cols = c(state, treat),
    names_from = year,
    values_from = cigsale,
    names_prefix = "cigsale_"
  )
outcome_dat
```


```{r}
dat_to_weight <- left_join(covs, outcome_dat)
dat_to_weight
```



```{r}
smoking_ebal
```



```{r}
dat_to_weight |> view()
```




```{r}
smoking_ebal <- weightit(
  treat ~ youth + beer_sales + cigsale_1975 + cigsale_1980 + cigsale_1988,
  data = dat_to_weight,
  estimand = "ATT",
  method = "ebal"
)
```

```{r}
lm_weightit(
  cigsale_1989 ~ treat,
  data = dat_to_weight,
  weightit = smoking_ebal
) |> coef()

lm_weightit(
  cigsale_1990 ~ treat,
  data = dat_to_weight,
  weightit = smoking_ebal
) |> coef()

lm_weightit(
  cigsale_1991 ~ treat,
  data = dat_to_weight,
  weightit = smoking_ebal
) |> coef()

lm_weightit(
  cigsale_1992 ~ treat,
  data = dat_to_weight,
  weightit = smoking_ebal
) |> coef()

lm_weightit(
  cigsale_1993 ~ treat,
  data = dat_to_weight,
  weightit = smoking_ebal
) |> coef()
```

