---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
```


```{r}
set.seed(42)
n = 100
dat <- tibble(y = sample(letters, n, replace = TRUE),
              z = sample(letters, n, replace = TRUE),
              w = rep("ok", n),
              treat = sample(0:1, n, replace = TRUE))
```



```{r}
find_small_counts <- function(dat, var, le, .by) {
  stopifnot(le >= 0)
  stopifnot(length(.by) == 1)
  stopifnot(length(var) == 1)
  
  var_sym <- ensym(var)
  by_sym  <- ensym(.by)
  
  dat |>
    group_by(!!by_sym) |>
    count(!!var_sym) |>
    pivot_wider(
      names_from  = !!by_sym,
      values_from = n,
      values_fill = 0,
      names_prefix = paste0(.by, "_")
    ) |>
    rowwise() |>
    mutate(min = min(c_across(2:last_col()))) |>
    ungroup() |>
    filter(min <= le) |>
    select(-min)
}
```


```{r}
find_all_small_counts <- function(dat, vars, le, .by) {
  vars |> map(~ find_small_counts(dat, .x, le, .by))
}
```


```{r}
remove_small_count <- function(dat, var, le, .by) {
  stopifnot(le >= 0)
  stopifnot(length(.by) == 1)
  stopifnot(length(var) == 1)

  var_sym <- ensym(var)

  remove_tab <- find_small_counts(dat, var, le, .by)
  print(remove_tab)

  remove_levels <- remove_tab |> pull(!!var_sym)
  
  dat |>
    filter_out(!!var_sym %in% remove_levels)
}
```



```{r}
remove_all_small_count <- function(dat, vars, le, .by) {
  res <- dat
  res_rows <- nrow(res)
  done <- FALSE
  loop <- 1
  while (!done) {
    glue::glue("Loop {loop}") |> message()

    for (var in vars) {
      glue::glue("Processing {var}") |> message()
      res <- res |> remove_small_count(var, le = le, .by = .by)
    }
    
    done <- res_rows == nrow(res)
    res_rows <- nrow(res)
    loop <- loop + 1
  }
  res
}
```



```{r}
res <- dat |>
  remove_all_small_count(c("y", "z", "w"), le = 0, .by = "treat")
```


```{r}
dat |> find_all_small_counts(c("y", "z", "w"), le = 0, .by = "treat")
```

```{r}
res |> find_all_small_counts(c("y", "z", "w"), le = 0, .by = "treat")
```

```{r}
nrow(res)
```







