---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE}
library(tidyverse)
library(GGally)
library(viridis)
library(quantmod)
library(patchwork)
library(smooth)
```



```{r}
covid_hosp <- read.csv("https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=covidOccupiedMVBeds&metric=hospitalCases&metric=newAdmissions&format=csv")
```

```{r}
View(covid_hosp)
```



```{r}
covid_dat <- read.csv("https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=newAdmissions&metric=newCasesBySpecimenDate&metric=newDeaths28DaysByDeathDate&metric=newVirusTests&format=csv")
```


```{r}
vax_dat <- read.csv("https://api.coronavirus.data.gov.uk/v2/data?areaType=overview&metric=cumVaccinationCompleteCoverageByPublishDatePercentage&metric=cumVaccinationFirstDoseUptakeByPublishDatePercentage&format=csv")
```


```{r}
dat <- left_join(covid_dat, vax_dat)
```


```{r}
names(dat)
```

```{r}
dat <- dat %>%
  mutate(
    vax_1st = ifelse(
      is.na(cumVaccinationFirstDoseUptakeByPublishDatePercentage),
      0, 
      cumVaccinationFirstDoseUptakeByPublishDatePercentage),
    vax_2nd = ifelse(
      is.na(cumVaccinationCompleteCoverageByPublishDatePercentage),
      0, 
      cumVaccinationCompleteCoverageByPublishDatePercentage)
  )
```



```{r fig.height=3, fig.width=7, dpi=300}
scatter_cases_admissions_1st_dose <- dat %>%
  ggplot(
    aes(newCasesBySpecimenDate, newAdmissions,
        colour = vax_1st)) +
  geom_point() +
  labs(colour = "% first dose",
       x = "Daily cases",
       y = "Daily hospital admissions") +
  scale_colour_steps()

scatter_cases_admissions_1st_dose
```


```{r fig.height=3, fig.width=7, dpi=300}
scatter_cases_admissions_2nd_dose <- dat %>%
  ggplot(
    aes(newCasesBySpecimenDate, newAdmissions,
        colour = vax_2nd)) +
  geom_point() +
  labs(colour = "% second dose",
       x = "Daily cases",
       y = "Daily hospital admissions") +
  scale_colour_steps()

scatter_cases_admissions_2nd_dose
```


```{r}
sma_order = 12

peaks_valleys_dat <- dat %>%
  select(
    date,
    newAdmissions,
    newCasesBySpecimenDate,
    newVirusTests,
    newDeaths28DaysByDeathDate
  ) %>%
  arrange(as.Date(date)) %>%
  mutate(i = 1:n())

peaks_valleys_dat_temp <- peaks_valleys_dat %>%
  select(i, newAdmissions) %>%
  na.omit()

peaks_valleys_dat_temp$newAdmissions_smooth =
  sma(peaks_valleys_dat_temp$newAdmissions,
      order = sma_order)$fitted

the_peaks <- peaks_valleys_dat_temp$i[
  findPeaks(peaks_valleys_dat_temp$newAdmissions_smooth,thresh = 2)]
the_valleys <- peaks_valleys_dat_temp$i[
  findValleys(peaks_valleys_dat_temp$newAdmissions_smooth, thresh = 2)]

switches <- c(1, the_peaks - sma_order,
                 the_valleys - sma_order,
              max(peaks_valleys_dat$i)) %>%
  sort()

switch_threshold <- 19
select_em <- c(TRUE, switches[-1] -
                 switches[-length(switches)] > switch_threshold)
switches <- switches[select_em]
plot(peaks_valleys_dat$newAdmissions)
abline(v = switches)
```




```{r}
peaks_valleys_dat <- peaks_valleys_dat %>% 
  mutate(date_segment = cut(i, switches, include.lowest = T))
```

```{r}
cut_dates <- peaks_valleys_dat %>%
  group_by(date_segment) %>%
  summarise(start_date = date %>% as.Date %>% min())

cut_dates$start_date
```


```{r}
levels(peaks_valleys_dat$date_segment) <- cut_dates$start_date
```



```{r}
date_range <- c(min(as.Date(peaks_valleys_dat$date)), as.Date("2021-08-01"))
```

```{r}
scatter_deaths_date_rainbow <- peaks_valleys_dat %>%
  ggplot(aes(as.Date(date), newDeaths28DaysByDeathDate, colour = date_segment)) +
      geom_point() +
      labs(x = "Date",
           y = "Daily deaths") +
  theme(legend.position = "none") +
  scale_x_date(
    date_labels = "%b %Y",
    limits = date_range)

scatter_deaths_date_rainbow
```

```{r}
scatter_admissions_date_rainbow <- peaks_valleys_dat %>%
  ggplot(aes(as.Date(date), newAdmissions, colour = date_segment)) +
      geom_point() +
      labs(x = "Date",
           y = "Daily hospital admissions") +
  theme(legend.position = "none") +
  scale_x_date(
    date_labels = "%b %Y",
    limits = date_range)

scatter_admissions_date_rainbow
```


```{r}
scatter_tests_date_rainbow <- peaks_valleys_dat %>%
  ggplot(aes(as.Date(date), newVirusTests/1000, colour = date_segment)) +
      geom_point() +
      labs(x = "Date",
           y = "Daily tests (1000s)") +
  theme(legend.position = "none") +
  scale_x_date(
    date_labels = "%b %Y",
    limits = date_range)

scatter_tests_date_rainbow
```

```{r}
scatter_cases_date_rainbow <- peaks_valleys_dat %>%
  ggplot(aes(as.Date(date),
             newCasesBySpecimenDate,
             colour = date_segment)) +
      geom_point() +
      labs(x = "Date",
           y = "Daily cases") +
  theme(legend.position = "none") +
  scale_x_date(
    date_labels = "%b %Y",
    limits = date_range)

scatter_cases_date_rainbow
```


```{r}
scatter_admissions_cases_rainbow <- peaks_valleys_dat %>%
  ggplot(
    aes(newCasesBySpecimenDate, newAdmissions,
        colour = date_segment)) +
  geom_point() +
  labs(x = "Daily cases",
       y = "Daily hospital admissions") +
  theme(legend.position = "none")

scatter_admissions_cases_rainbow
```


```{r}
View(peaks_valleys_dat)
```



```{r}
scatter_deaths_cases_rainbow <- peaks_valleys_dat %>%
  ggplot(
    aes(newCasesBySpecimenDate, newDeaths28DaysByDeathDate,
        colour = date_segment)) +
  geom_point() +
  labs(x = "Daily cases",
       y = "Daily deaths") +
  theme(legend.position = "none")

scatter_deaths_cases_rainbow
```


```{r}
scatter_admissions_deaths <- peaks_valleys_dat %>%
  ggplot(
    aes(newAdmissions, newDeaths28DaysByDeathDate,
        colour = date_segment)) +
  geom_point() +
  labs(x = "Daily hospital admissions",
       y = "Daily deaths") +
  theme(legend.position = "none")

scatter_admissions_deaths
```




```{r fig.height=5, fig.width=9, dpi=300}
(scatter_admissions_date_rainbow/
   scatter_admissions_cases_rainbow) |
  (scatter_cases_admissions_1st_dose/
     scatter_cases_admissions_2nd_dose)
```




```{r fig.height=5, fig.width=8, dpi=300}
(scatter_cases_date_rainbow /
   (scatter_admissions_deaths + geom_smooth(se = FALSE)) | 
(scatter_admissions_cases_rainbow +
          geom_smooth(se = FALSE)) /
   (scatter_deaths_cases_rainbow +
          geom_smooth(se = FALSE)))
```


```{r fig.height=6, fig.width=8, dpi=300}
(scatter_cases_date_rainbow /
   scatter_tests_date_rainbow /
  scatter_admissions_date_rainbow) | 
((scatter_admissions_cases_rainbow +
          geom_smooth(se = FALSE)) /
   (scatter_deaths_cases_rainbow +
          geom_smooth(se = FALSE))/
   scatter_deaths_date_rainbow)
```



```{r}
mod_deaths <- lm(
  newDeaths28DaysByDeathDate ~
    newCasesBySpecimenDate:date_segment + date_segment - 1,
  data = peaks_valleys_dat
)
coef(mod_deaths) %>% round(6)
```

```{r}
mod_hosp <- lm(
  newAdmissions ~ newCasesBySpecimenDate:date_segment + date_segment -1,
  data = peaks_valleys_dat)
coef(mod_hosp) %>% round(5)
```


```{r}
last_date <- peaks_valleys_dat$date_segment %>%
  levels() %>% 
  sort() %>%
  last()
```


```{r}
last_seg <- peaks_valleys_dat %>%
  filter(date_segment == last_date)
last_seg
```


```{r}
last_seg_deaths <- lm(
  newDeaths28DaysByDeathDate ~ newCasesBySpecimenDate,
  data = last_seg
)
summary(last_seg_deaths)
coef(last_seg_deaths)
```




```{r}
last_seg_admissions <- lm(
  newAdmissions ~ newCasesBySpecimenDate,
  data = last_seg
)
summary(last_seg_admissions)
coef(last_seg_admissions)
```

Admissions / cases (%)

```{r}
(coef(last_seg_admissions)[2] * 100) %>% round(2)
```

Deaths / cases (%)

```{r}
(coef(last_seg_deaths)[2] * 100) %>% round(2)
```


```{r}
predict(last_seg_admissions,
        newdat = data.frame(newCasesBySpecimenDate = 100e3))
```


```{r}
predict(last_seg_deaths,
        newdat = data.frame(newCasesBySpecimenDate = 100e3))
```


```{r}
last_seg %>%
  ggplot(aes(newCasesBySpecimenDate, newAdmissions)) +
  geom_point()
```

```{r}
last_seg %>%
  ggplot(aes(newCasesBySpecimenDate, newDeaths28DaysByDeathDate )) +
  geom_point()
```

```{r}
last_seg %>%
  ggplot(aes(newAdmissions, newDeaths28DaysByDeathDate)) +
  geom_point()
```


```{r}
gpairs_lower <- function(g){
  g$plots <- g$plots[-(1:g$nrow)]
  g$yAxisLabels <- g$yAxisLabels[-1]
  g$nrow <- g$nrow -1

  g$plots <- g$plots[-(seq(g$ncol, length(g$plots), by = g$ncol))]
  g$xAxisLabels <- g$xAxisLabels[-g$ncol]
  g$ncol <- g$ncol - 1

  g
}
```


```{r fig.height=6, fig.width=8}
to_plot <- peaks_valleys_dat %>%
  select(
    date,
    newCasesBySpecimenDate,
    newAdmissions,
    newDeaths28DaysByDeathDate,
    date_segment
  ) %>%
  mutate(date = as.Date(date),
         newCasesBySpecimenDate = newCasesBySpecimenDate / 1000)

to_plot %>%
  ggpairs(columns = 1:(ncol(to_plot) - 1),
          mapping = aes(colour = date_segment),
          lower  = list(continuous = "points"),
          upper  = list(continuous = "blank"),
          diag  = list(continuous = "blankDiag"),
          columnLabels = c("Date",
                           "Cases (1000s)",
                           "Hospitalisations",
                           "Deaths")) %>%
  gpairs_lower()
```











