---
title: "UK crime data test"
author: "Andi Fugard"
output: html_notebook
---


```{r}
library(ukpolice)
library(tidyverse)
library(leaflet)
library(leaflet.extras)
```




```{r}
date_df <- expand.grid(year = 2020:2021,
                       month = 1:12)
```


```{r}
dates <- paste0(date_df$year, "-",
                str_pad(date_df$month, width = 2, pad = "0"))
dates
```


```{r}
local_crimes_mh <- lapply(dates,
                       \(d) ukc_crime_coord(lat = 51.5709,
                                            lng = -0.0960,
                                            date = d)) %>%
  bind_rows()
```


```{r}
local_crimes_mh
```


```{r}
local_crimes_mh %>%
  group_by(category) %>%
  summarise(n = n()) %>%
  mutate(perc = (n*100/sum(n)) %>% round(0)) %>%
  arrange(desc(perc))
```




```{r}
local_crimes_mh %>%
  leaflet() %>%
  addTiles() %>%
  addHeatmap(
    lng = ~ longitude %>% as.numeric(),
    lat = ~ latitude  %>% as.numeric()
  )
```


```{r}
map_crimes <- function(dat) {
  dat %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    lng = ~ longitude %>% as.numeric() %>% jitter(),
    lat = ~ latitude  %>% as.numeric() %>% jitter(),
    popup = ~ paste0(
      "<B>", category, "</B>",
      "<BR>",
      street_name,
      "<BR>",
      month,
      "<BR><BR>",
      "Outcome: ", outcome_status_category,
      "<BR>(",
      outcome_status_date, ")"
    ),
    radius = 1
  )
}
```




```{r}
local_crimes_mh %>%
  map_crimes()
```


```{r}
num_10_crimes <- lapply(dates,
                       \(d) ukc_crime_coord(lat = 51.5034,
                                            lng = -0.1276,
                                            date = d)) %>%
  bind_rows()
```

```{r}
num_10_crimes %>%
  map_crimes()
```


```{r}
num_10_crimes %>%
  filter(str_detect(street_name, "On or near Downing Street")) %>%
  group_by(month, category) %>%
  summarise(n = n())
```


